### ISSUE TITLE
Error executing scfript

### ISSUE THREAD

**Issue by KOTIJim** [florianbeer/grafana-netatmo#14]
This was working until 5 day ago, now I get this error (nothing in my environment changed):

Traceback (most recent call last):
  File "netatmo_influx.py", line 36, in <module>
    for module, moduleData in weatherData.lastData(station=station_name, exclude=3600).items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by florianbeer** [comment]
Upgrade to the latest version of the [lnetatmo](https://github.com/philippelt/netatmo-api-python) library `pip3 install --upgrade lnetatmo`
