### ISSUE TITLE
grafana-netatmo.py no longer works with updated lnetatmo module

### ISSUE THREAD

**Issue by baiti** [florianbeer/grafana-netatmo#15]
Yesterday the old authentication procedure stopped working, so I had to update to the latest version of `lnetatmo`, however this version has a new definition for `lastData` so the following no longer works:

`for module, moduleData in weatherData.lastData(station=station, exclude=0).items():`

The parameter `station` no longer exists. It throws a type error:

```
Traceback (most recent call last):
  File "./netatmo_influx.py", line 46, in <module>
    for module, moduleData in weatherData.lastData(station=station, exclude=0).items():
TypeError: lastData() got an unexpected keyword argument 'station'
```

I got it back working by just dropping that `station` agrument.

**Comment by baiti** [comment]
Let me add to the subject: The concept of dropping  the station parameter only works if only **one** station is queried. In my case I am querying two stations, however, the arrays that are constructed for being submitted into influxdb contain the same values for both stations. So it really doesn't help to just drop that parameter. The question would be, why has `lnetatmo` changed? I know that question doesn't really belong into a `grafana-netatmo` issue but it needs to be resolved somehow.

**Comment by vlsoft** [comment]
+1 
I have the same problem

**Comment by baiti** [comment]
Actually,Phillipe, the owner of the `lnetatmo` package has made a fix to bring the station parmeter back. Check this out:
[https://github.com/philippelt/netatmo-api-python/issues/50](https://github.com/philippelt/netatmo-api-python/issues/50)
