### ISSUE TITLE
Access Token/ Refresh Token // Script not working for me

### ISSUE THREAD

**Issue by LeckerKuchen** [florianbeer/grafana-netatmo#17]
Hi Florian,

thanks for updating the script as the old authentification stopped working just a few days ago. However I get the following errormessage and do not know what to do next...
![grafik](https://github.com/florianbeer/grafana-netatmo/assets/66876295/af113f1b-13e6-44e1-81a7-e7c40947523a)

Just out of a curiosity: The new script implements the refresh token, but doesnt the access token needs to be used aswell?

**Comment by rvk01** [comment]
Did you get the latest version of lnetatmo? (it changed a few times over the last days).

The script uses the non-expiring refresh_token (which you got from the web-console) to get a access_token. The access_token will expire after 3 hours. The script will only use that access_token while running (and get a new one when restarted). It should actually reuse the old access_token when restarting (as good behavior) but it doesn't. Hopefully netatmo doesn't care about recreating the access_token each time (or you need to make your script ever-running).

**Comment by LeckerKuchen** [comment]
hi rvk01,

thank you, indeed I did not update lnetatmo. After doing so (and also entering the oauth2 credentials in lnetatmo.py) I am getting a step further, but am still left with the following new error message:
![grafik](https://github.com/florianbeer/grafana-netatmo/assets/66876295/3b131fd1-eef4-493f-92dc-a154e1e0f496)

Can you give any further advice on that?

Thanks!

**Comment by rvk01** [comment]
> Can you give any further advice on that?

Yeah. Everything keeps changing.

For now you can change this line in netatmo_influx.py:
`station = weatherData.stationById(station)`
into this:
`station = weatherData.stationByName(station)`

**Comment by LeckerKuchen** [comment]
You made my day, mate!
It is working again.
Big thanks!!

6 out of 5 stars ♥
