### ISSUE TITLE
Lnetatmo package broke netatmo_influx.py

### ISSUE THREAD

**Issue by aolik08** [florianbeer/grafana-netatmo#18]
After the last upgrade of lnetatmo package, it seems that there is no way to get the info for the weather station anymore. I do not know which change broke the authentication:

```
 Traceback (most recent call last):
  File "/usr/local/bin/netatmo_influx.py", line 31, in <module>
    station_name = station['station_name']
TypeError: 'NoneType' object is not subscriptable
```

https://github.com/philippelt/netatmo-api-python/compare/v3.0.0...v3.2.0

**Comment by psykok** [comment]
I was able to fixe this issue by changing :
`station = weatherData.stationById(station)`
by
`station = weatherData.stationByName(station)`

**Comment by aolik08** [comment]
thank you
