### ISSUE TITLE
Unexpexted keyword error with refreshToken

### ISSUE THREAD

**Issue by tjantunen** [florianbeer/grafana-netatmo#19]
I just upgraded the script to latest and provided all needed authentication information but when running script, I get the following error:

pi@raspberry:/usr/local/bin $ ./netatmo_influx.py

Traceback (most recent call last):
  File "/usr/local/bin/./netatmo_influx.py", line 11, in <module>
    authorization = lnetatmo.ClientAuth(
TypeError: __init__() got an unexpected keyword argument 'refreshToken'

My python version is: 3.9.2

**Comment by rvk01** [comment]
Did you also update to the latest version of lnetatmo from https://github.com/philippelt/netatmo-api-python.git ?

**Comment by tjantunen** [comment]
I upgraded that one now but then I got following error:

pi@raspberry:/usr/local/bin $ ./netatmo_influx.py
Traceback (most recent call last):
  File "/usr/local/bin/./netatmo_influx.py", line 27, in <module>
    station_name = station['station_name']
TypeError: 'NoneType' object is not subscriptable

**Comment by rvk01** [comment]
I think there still an error in grafana_netatmo.py.

You can try changing the line with stationById to stationByName.

**Comment by tjantunen** [comment]
thanks, this did the trick and its working now.
