### ISSUE TITLE
Station name not centered

### ISSUE THREAD

**Issue by dkozinn** [florianbeer/grafana-netatmo#3]
Using Grafana 7.0.6, the station name doesn't appear centered (as it is in your screenshot). I tried tinkering around myself but couldn't get it to work. I'm not sure if this is an issue with the panel or possibly something in this version of Grafana.

Obviously this is a purely cosmetic issue. In the attached screenshot I've turned transparency off to highlight the size of the panel.
![2020-07-11_16-00-50](https://user-images.githubusercontent.com/8498054/87232898-9c1bdc80-c390-11ea-9ea3-dc29f568c215.jpg)

(I've also converted to US units for us heathens that still don't use metric)

**Comment by florianbeer** [comment]
I wasn't aware that Netatmo could switch to non-metric units. That's nice :)

To center the station name I have the following HTML snippet in my panel:
```
<div style="height:100%;display:flex;justify-content:center;align-items:center;">
<h1 style="font-size:300%;font-weight:bold;">$Station</h1>
</div>
```

**Comment by dkozinn** [comment]
You can't actually switch the device to non-metric units, but I modified the query to have some math built in to do the conversions:
`SELECT "value" *3.28084 FROM "altitude" WHERE ("station" =~ /^$Station$/) AND $timeFilter`

I'm using the same HTML as you to try to get that centered, and I just can't figure out why it's not working for me. I've set up a simple web page with that exact code and it does seem to work. I'll have to use something like Chrome developer tools to figure out what's going on. What version of Grafana are you using? I'm on 7.1. 

What I've started doing is to use your work as a basis for my own dashboard. I've got rain & wind modules, and the repeating template didn't work for those. I decided that instead of using templates, I'd create separate rows for each type of module. That way I can show wind speed & direction, and so on. It's very much a work in progress. I'm also going to move what I think of as the device status info (battery state, rf state) to a separate dashboard since things were getting crowded.

As the result of this, one things that does change is that my queries now look for a (case-insensitive) string specific to that module. For example, here's the outdoor temperature query:

`SELECT last("value") *1.8+32 FROM "temperature" WHERE ("module" =~ /(?i)outdoor/ AND "station" =~ /^$Station$/) AND $timeFilter GROUP BY time(5m), "module", "station" fill(previous)`

The only downside to what I've done is that it is somewhat more specific in the requirements compared to what you've done. Specifically, for my dashboard the indoor module has to have "indoor" as part of it's name, and "outdoor", "rain", "wind" for those modules. It also no longer would handle multiple indoor modules. (Although of course those could be added manually).

When I (eventually) finish I will probably make it available with credit given you to for the inspiration, and thank you again.

**Comment by florianbeer** [comment]
Nice, maybe you could create a fork incorporating your non-metric and rain & wind changes.
