### ISSUE TITLE
API change breaks station selection

### ISSUE THREAD

**Issue by dkozinn** [florianbeer/grafana-netatmo#8]
Netatmo has apparently changed their API as explained [here](https://forum.netatmo.com/viewtopic.php?f=5&t=19196). This had the unfortunate side-effect of changing the station name. For example, if the name of the station was previously "David" the new station name looks like "David (Indoor Module)". As a result, there are now two different tags with one that has data up to the change and one has data after it. At first glance at least a temporary fix would be to change any query that includes 

`station =~/^$Station$/`
to
`station =~/^$Station$*/`

adding the '*' on the end.

This is a workaround, since they say that station_name is deprecated in favor of home_name. The API documentation doesn't seem to spell this out but you can see the new (?) fields when playing with the API at https://dev.netatmo.com/apidocumentation/weather#getstationsdata

**Comment by florianbeer** [comment]
Thanks, I was wondering why the dashboard in my home (which uses bits of this full dashboard) suddenly shows N/A but didn't have time to investigate yet.

Open source development is a wonderful thing :) 

I think I'll implement the workaround now and then dive deeper into how to adapt to the API changes on the weekend.

**Comment by dkozinn** [comment]
It was bugging me and as I don't visit the Netatmo forums that often I didn't notice it. There are some other cosmetic issues that the wildcard doesn't fix. For example, some of the meter-type graphs wind up showing two instead of one where  there's an overlap in the names. There's likely a fix for that but it's not much of an issue once the older data isn't in view. I think there might be a few other odd problems as I just did a global search and replace in the XML and it seemed to work well enough.

I'll be interested to see what you're able to come up with.

**Comment by florianbeer** [comment]
From what I can see on my local installation, it should be enough to just select the new station name in the dropdown on the top right and all graphs are working again.

Closing this for now, but I will still investigate the API changes and see if I might make some (breaking) changes to adapt to the new schema.
