### ISSUE TITLE
TypeError: lastData() got an unexpected keyword argument 'station'

### ISSUE THREAD

**Issue by todrees1967** [florianbeer/grafana-netatmo#9]
Hi, trying to execute the script, I am facing this error:

Traceback (most recent call last):
  File "netatmo_influx.py", line 39, in <module>
    for module, moduleData in weatherData.lastData(station=station_name, exclude=3600).items():
TypeError: lastData() got an unexpected keyword argument 'station'

Any idea, what causes this error message?

Thanks and Regards,
Torsten

**Comment by FeroXz** [comment]
Same here

**Comment by todrees1967** [comment]
Is this project no longer maintained? Seems, I am not the only one, that has this problem.

**Comment by karaktaka** [comment]
This error is from an version update of lnetatmo. The last version I used was 1.6.0 and it worked with it. You may want to downgrade the package.

**Comment by todrees1967** [comment]
> This error is from an version update of lnetatmo. The last version I used was 1.6.0 and it worked with it. You may want to downgrade the package.

Can you please let me know, how to downgrade to the 1.6.0 version of lnetatmo?

**Comment by karaktaka** [comment]
pip install --upgrade lnetatmo==1.6.0

Don't get caught by the word upgrade, pip can upgrade and downgrade packages with the upgrade flag.

**Comment by todrees1967** [comment]
Great! With 1.6.0 there's no problem with the script.
